## 导入数据

In [1]:
import pandas as pd

In [9]:
pd.read_csv('C:\\Users\\Administrator\\Desktop\\cev.csv')

     Unnamed: 0    Y   X1   X2   X3
0             1  5.1  3.5  1.4  0.2
1             2  4.9  3.0  1.4  0.2
2             3  4.7  3.2  1.3  0.2
3             4  4.6  3.1  1.5  0.2
4             5  5.0  3.6  1.4  0.2
5             6  5.4  3.9  1.7  0.4
6             7  4.6  3.4  1.4  0.3
7             8  5.0  3.4  1.5  0.2
8             9  4.4  2.9  1.4  0.2
9            10  4.9  3.1  1.5  0.1
10           11  5.4  3.7  1.5  0.2
11           12  4.8  3.4  1.6  0.2
12           13  4.8  3.0  1.4  0.1
13           14  4.3  3.0  1.1  0.1
14           15  5.8  4.0  1.2  0.2
15           16  5.7  4.4  1.5  0.4
16           17  5.4  3.9  1.3  0.4
17           18  5.1  3.5  1.4  0.3
18           19  5.7  3.8  1.7  0.3
19           20  5.1  3.8  1.5  0.3
20           21  5.4  3.4  1.7  0.2
21           22  5.1  3.7  1.5  0.4
22           23  4.6  3.6  1.0  0.2
23           24  5.1  3.3  1.7  0.5
24           25  4.8  3.4  1.9  0.2
25           26  5.0  3.0  1.6  0.2
26           27  5.0  3.4  1.6  0.4
27           28  5.2  3.5  1.5  0.2
28           29  5.2  3.4  1.4  0.2
29           30  4.7  3.2  1.6  0.2
..          ...  ...  ...  ...  ...
120         121  6.9  3.2  5.7  2.3
121         122  5.6  2.8  4.9  2.0
122         123  7.7  2.8  6.7  2.0
123         124  6.3  2.7  4.9  1.8
124         125  6.7  3.3  5.7  2.1
125         126  7.2  3.2  6.0  1.8
126         127  6.2  2.8  4.8  1.8
127         128  6.1  3.0  4.9  1.8
128         129  6.4  2.8  5.6  2.1
129         130  7.2  3.0  5.8  1.6
130         131  7.4  2.8  6.1  1.9
131         132  7.9  3.8  6.4  2.0
132         133  6.4  2.8  5.6  2.2
133         134  6.3  2.8  5.1  1.5
134         135  6.1  2.6  5.6  1.4
135         136  7.7  3.0  6.1  2.3
136         137  6.3  3.4  5.6  2.4
137         138  6.4  3.1  5.5  1.8
138         139  6.0  3.0  4.8  1.8
139         140  6.9  3.1  5.4  2.1
140         141  6.7  3.1  5.6  2.4
141         142  6.9  3.1  5.1  2.3
142         143  5.8  2.7  5.1  1.9
143         144  6.8  3.2  5.9  2.3
144         145  6.7  3.3  5.7  2.5
145         146  6.7  3.0  5.2  2.3
146         147  6.3  2.5  5.0  1.9
147         148  6.5  3.0  5.2  2.0
148         149  6.2  3.4  5.4  2.3
149         150  5.9  3.0  5.1  1.8

[150 rows x 5 columns]

In [11]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
# 创建一个Series通过传递值的列表，让大熊猫创建一个默认的整数索引：
s =pd.Series([1,3,5,np.nan,6,8])

In [15]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [16]:
# DataFrame通过传递带有日期时间索引和标签列的NumPy数组创建一个：
dates = pd.date_range('20130101',periods = 6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [18]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

                   A         B         C         D
2013-01-01  1.155691 -1.346379 -1.876744  1.070130
2013-01-02 -1.303769  0.516142 -1.762249  0.759016
2013-01-03  1.069799  0.518984  0.931027 -0.199281
2013-01-04  0.314681 -0.303413 -2.385402 -0.425625
2013-01-05 -0.729826  2.276358 -0.959687 -1.843515
2013-01-06 -0.692828 -1.828158 -0.472407  0.298597

In [27]:
df2  = pd.DataFrame({
    'A':1.,
    'B': pd.Timestamp('20130102'),
    'C':pd.Series(1,index=list(range(4)),dtype='float32'),
    'D': np.array([3]*4,dtype='int32'),
    'E': pd.Categorical(['test','train','test','train']),
    'F': 'foo'
})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [28]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [32]:
#查看头部
df.head(3)

                   A         B         C         D
2013-01-01  1.155691 -1.346379 -1.876744  1.070130
2013-01-02 -1.303769  0.516142 -1.762249  0.759016
2013-01-03  1.069799  0.518984  0.931027 -0.199281

In [33]:
#查看尾部
df.tail(3)

                   A         B         C         D
2013-01-04  0.314681 -0.303413 -2.385402 -0.425625
2013-01-05 -0.729826  2.276358 -0.959687 -1.843515
2013-01-06 -0.692828 -1.828158 -0.472407  0.298597

In [35]:
# 显示索引，列和底层的NumPy数据：
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [36]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [37]:
df.values

array([[ 1.15569113, -1.34637893, -1.8767442 ,  1.07013023],
       [-1.3037694 ,  0.51614167, -1.76224869,  0.75901645],
       [ 1.06979861,  0.51898432,  0.93102655, -0.19928135],
       [ 0.31468102, -0.30341337, -2.38540176, -0.42562534],
       [-0.72982551,  2.27635784, -0.9596866 , -1.84351453],
       [-0.69282824, -1.82815824, -0.47240732,  0.2985965 ]])

In [41]:
# describe() 显示您的数据的快速统计摘要：
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.031042 -0.027744 -1.087577 -0.056780
std    1.028183  1.480533  1.202653  1.040242
min   -1.303769 -1.828158 -2.385402 -1.843515
25%   -0.720576 -1.085638 -1.848120 -0.369039
50%   -0.189074  0.106364 -1.360968  0.049658
75%    0.881019  0.518274 -0.594227  0.643911
max    1.155691  2.276358  0.931027  1.070130

In [42]:
#转置
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.155691   -1.303769    1.069799    0.314681   -0.729826   -0.692828
B   -1.346379    0.516142    0.518984   -0.303413    2.276358   -1.828158
C   -1.876744   -1.762249    0.931027   -2.385402   -0.959687   -0.472407
D    1.070130    0.759016   -0.199281   -0.425625   -1.843515    0.298597

In [43]:
df

                   A         B         C         D
2013-01-01  1.155691 -1.346379 -1.876744  1.070130
2013-01-02 -1.303769  0.516142 -1.762249  0.759016
2013-01-03  1.069799  0.518984  0.931027 -0.199281
2013-01-04  0.314681 -0.303413 -2.385402 -0.425625
2013-01-05 -0.729826  2.276358 -0.959687 -1.843515
2013-01-06 -0.692828 -1.828158 -0.472407  0.298597

In [48]:
#按轴排序
df.sort_index(axis=1,ascending=False)

                   D         C         B         A
2013-01-01  1.070130 -1.876744 -1.346379  1.155691
2013-01-02  0.759016 -1.762249  0.516142 -1.303769
2013-01-03 -0.199281  0.931027  0.518984  1.069799
2013-01-04 -0.425625 -2.385402 -0.303413  0.314681
2013-01-05 -1.843515 -0.959687  2.276358 -0.729826
2013-01-06  0.298597 -0.472407 -1.828158 -0.692828

In [49]:
#按值进行排序
df.sort_values(by='B')

                   A         B         C         D
2013-01-06 -0.692828 -1.828158 -0.472407  0.298597
2013-01-01  1.155691 -1.346379 -1.876744  1.070130
2013-01-04  0.314681 -0.303413 -2.385402 -0.425625
2013-01-02 -1.303769  0.516142 -1.762249  0.759016
2013-01-03  1.069799  0.518984  0.931027 -0.199281
2013-01-05 -0.729826  2.276358 -0.959687 -1.843515

In [25]:
#获取数据
df[]

In [20]:
list(range(4))

[0, 1, 2, 3]

In [56]:
pd.read_excel('C:\\Users\\Administrator\\Desktop\\加和科技\\Loreal\\Y2018 L’Oréal Programmatic Weekly Report till Jun.26.xlsx')

                                               Y2018 L'Oréal Programmatic OTV Rawdata  \
NaN NaN                  NaN                                                      NaN
    NaN                  NaN                                                      NaN
NaN Brand                L'Oréal                                                  NaN
    Cut-off Date         2018-06-25 00:00:00                                      NaN
    Ratio of Seletctable Imgotv                                                 1.5：1
    NaN                  Youku&Tudou                                            1.5：1
                         Sohu                                        2:1（BJ/SH 1.5:1）
                         IQIYI                                                  1.5：1
                         PPTV                                                   1.5：1
                         LeTV                                                   1.5：1
                         Tencent                         2:1（BJ/SH 1.2:1，HZ/NJ 1.5:1）
                         NaN                                                      NaN
                         NaN                                                      NaN
    Summary：             NaN                                                      NaN
    媒体                   活动状况                                                     NaN
    Imgotv               个别活动未超量推送。                                               NaN
    NaN                  个别活动推送有效PV小于排期推送量。                                       NaN
                         部分活动未完成曝光。                                               NaN
                         个别活动秒针监测首周超频较高。                                          NaN
                         大部分活动秒针监测Unstable%较高。                                    NaN
    IQIYI                个别活动未超量推送。                                               NaN
    NaN                  个别活动推送有效PV小于排期推送量。                                       NaN
                         大部分活动未完成曝光。                                              NaN
                         个别活动秒针监测首周超频较高。                                          NaN
                         个别活动秒针监测Unstable%较高。                                     NaN
    PPTV                 部分活动未超量推送。                                               NaN
    NaN                  大部分活动推送有效PV小于排期推送量。                                      NaN
                         大部分活动未完成曝光。                                              NaN
                         个别活动秒针监测首周超频较高。                                          NaN
                         各活动秒针监测Unstable%较高。                                      NaN
    Sohu                 各活动均超量推送。                                                NaN
    NaN                  个别活动推送有效PV小于排期推送量。                                       NaN
                         个别活动未完成曝光。                                               NaN
                         部分活动秒针监测首周超频较高。                                          NaN
                         大活动秒针监测Unstable%较高。                                      NaN
    Tencent              各活动均超量推送。                                                NaN
    NaN                  各活动推送有效PV大于排期推送量。                                        NaN
                         个别活动未完成曝光。                                               NaN
                         个别活动秒针监测首周超频较低。                                          NaN
                         各活动秒针监测Unstable%较低。                                      NaN
    YouTu                个别活动未超量推送。                                               NaN
    NaN                  个别活动推送有效PV小于排期推送量。                                       NaN
                         大部分活动未完成曝光。                                              NaN
                         除YSL,各活动秒针监测首周超频较低。                                      NaN
                         个别活动秒针监测Unstable%较高。                                     NaN

                                                Unnamed: 1  \
NaN NaN                  NaN                           NaN
    NaN                  NaN                           NaN
NaN Brand                L'Oréal                       NaN
    Cut-off Date         2018-06-25 00:00:00           NaN
    Ratio of Seletctable Imgotv                        NaN
    NaN                  Youku&Tudou                   NaN
                         Sohu                          NaN
                         IQIYI                         NaN
                         PPTV                          NaN
                         LeTV                          NaN
                         Tencent                       NaN
                         NaN                           NaN
                         NaN                           NaN
    Summary：             NaN                           NaN
    媒体                   活动状况                          NaN
    Imgotv               个别活动未超量推送。                    NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN
                         部分活动未完成曝光。                    NaN
                         个别活动秒针监测首周超频较高。               NaN
                         大部分活动秒针监测Unstable%较高。         NaN
    IQIYI                个别活动未超量推送。                    NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN
                         大部分活动未完成曝光。                   NaN
                         个别活动秒针监测首周超频较高。               NaN
                         个别活动秒针监测Unstable%较高。          NaN
    PPTV                 部分活动未超量推送。                    NaN
    NaN                  大部分活动推送有效PV小于排期推送量。           NaN
                         大部分活动未完成曝光。                   NaN
                         个别活动秒针监测首周超频较高。               NaN
                         各活动秒针监测Unstable%较高。           NaN
    Sohu                 各活动均超量推送。                     NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN
                         个别活动未完成曝光。                    NaN
                         部分活动秒针监测首周超频较高。               NaN
                         大活动秒针监测Unstable%较高。           NaN
    Tencent              各活动均超量推送。                     NaN
    NaN                  各活动推送有效PV大于排期推送量。             NaN
                         个别活动未完成曝光。                    NaN
                         个别活动秒针监测首周超频较低。               NaN
                         各活动秒针监测Unstable%较低。           NaN
    YouTu                个别活动未超量推送。                    NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN
                         大部分活动未完成曝光。                   NaN
                         除YSL,各活动秒针监测首周超频较低。           NaN
                         个别活动秒针监测Unstable%较高。          NaN

                                                                                  Unnamed: 2  \
NaN NaN                  NaN                                                             NaN
    NaN                  NaN                                                             NaN
NaN Brand                L'Oréal                                                         NaN
    Cut-off Date         2018-06-25 00:00:00                                             NaN
    Ratio of Seletctable Imgotv                                                          NaN
    NaN                  Youku&Tudou                                                     NaN
                         Sohu                                                            NaN
                         IQIYI                                                           NaN
                         PPTV                                                            NaN
                         LeTV                                                            NaN
                         Tencent                                                         NaN
                         NaN                                                             NaN
                         NaN                                                             NaN
    Summary：             NaN                                                             NaN
    媒体                   活动状况                                                             建议
    Imgotv               个别活动未超量推送。             Push媒体加大推送量&Push媒体控制频次&Push媒体控制推送资源中Stable%
    NaN                  个别活动推送有效PV小于排期推送量。                                              NaN
                         部分活动未完成曝光。                                                      NaN
                         个别活动秒针监测首周超频较高。                                                 NaN
                         大部分活动秒针监测Unstable%较高。                                           NaN
    IQIYI                个别活动未超量推送。                                              Push媒体加大推送量
    NaN                  个别活动推送有效PV小于排期推送量。                                              NaN
                         大部分活动未完成曝光。                                                     NaN
                         个别活动秒针监测首周超频较高。                                                 NaN
                         个别活动秒针监测Unstable%较高。                                            NaN
    PPTV                 部分活动未超量推送。             Push媒体加大推送量&Push媒体控制频次&Push媒体控制推送资源中Stable%
    NaN                  大部分活动推送有效PV小于排期推送量。                                             NaN
                         大部分活动未完成曝光。                                                     NaN
                         个别活动秒针监测首周超频较高。                                                 NaN
                         各活动秒针监测Unstable%较高。                                             NaN
    Sohu                 各活动均超量推送。              Push媒体加大推送量&Push媒体控制频次&Push媒体控制推送资源中Stable%
    NaN                  个别活动推送有效PV小于排期推送量。                                              NaN
                         个别活动未完成曝光。                                                      NaN
                         部分活动秒针监测首周超频较高。                                                 NaN
                         大活动秒针监测Unstable%较高。                                             NaN
    Tencent              各活动均超量推送。                                               Push媒体加大推送量
    NaN                  各活动推送有效PV大于排期推送量。                                               NaN
                         个别活动未完成曝光。                                                      NaN
                         个别活动秒针监测首周超频较低。                                                 NaN
                         各活动秒针监测Unstable%较低。                                             NaN
    YouTu                个别活动未超量推送。                                              Push媒体加大推送量
    NaN                  个别活动推送有效PV小于排期推送量。                                              NaN
                         大部分活动未完成曝光。                                                     NaN
                         除YSL,各活动秒针监测首周超频较低。                                             NaN
                         个别活动秒针监测Unstable%较高。                                            NaN

                                                Unnamed: 3  Unnamed: 4
NaN NaN                  NaN                           NaN         NaN
    NaN                  NaN                           NaN         NaN
NaN Brand                L'Oréal                       NaN         NaN
    Cut-off Date         2018-06-25 00:00:00           NaN         NaN
    Ratio of Seletctable Imgotv                        NaN         NaN
    NaN                  Youku&Tudou                   NaN         NaN
                         Sohu                          NaN         NaN
                         IQIYI                         NaN         NaN
                         PPTV                          NaN         NaN
                         LeTV                          NaN         NaN
                         Tencent                       NaN         NaN
                         NaN                           NaN         NaN
                         NaN                           NaN         NaN
    Summary：             NaN                           NaN         NaN
    媒体                   活动状况                          NaN         NaN
    Imgotv               个别活动未超量推送。                    NaN         NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN         NaN
                         部分活动未完成曝光。                    NaN         NaN
                         个别活动秒针监测首周超频较高。               NaN         NaN
                         大部分活动秒针监测Unstable%较高。         NaN         NaN
    IQIYI                个别活动未超量推送。                    NaN         NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN         NaN
                         大部分活动未完成曝光。                   NaN         NaN
                         个别活动秒针监测首周超频较高。               NaN         NaN
                         个别活动秒针监测Unstable%较高。          NaN         NaN
    PPTV                 部分活动未超量推送。                    NaN         NaN
    NaN                  大部分活动推送有效PV小于排期推送量。           NaN         NaN
                         大部分活动未完成曝光。                   NaN         NaN
                         个别活动秒针监测首周超频较高。               NaN         NaN
                         各活动秒针监测Unstable%较高。           NaN         NaN
    Sohu                 各活动均超量推送。                     NaN         NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN         NaN
                         个别活动未完成曝光。                    NaN         NaN
                         部分活动秒针监测首周超频较高。               NaN         NaN
                         大活动秒针监测Unstable%较高。           NaN         NaN
    Tencent              各活动均超量推送。                     NaN         NaN
    NaN                  各活动推送有效PV大于排期推送量。             NaN         NaN
                         个别活动未完成曝光。                    NaN         NaN
                         个别活动秒针监测首周超频较低。               NaN         NaN
                         各活动秒针监测Unstable%较低。           NaN         NaN
    YouTu                个别活动未超量推送。                    NaN         NaN
    NaN                  个别活动推送有效PV小于排期推送量。            NaN         NaN
                         大部分活动未完成曝光。                   NaN         NaN
                         除YSL,各活动秒针监测首周超频较低。           NaN         NaN
                         个别活动秒针监测Unstable%较高。          NaN         NaN